### ISSUE TITLE
ModuleNotFoundError: No module named 'giscanner._giscanner'

### ISSUE THREAD

**Issue by yummy527** [puxplaying/mutter-x11-scaling#37]
when I run "makepkg -si" after a while, got an error.

```shell
Found ninja-1.11.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/wxl/Downloads/mutter-x11-scaling/src/build
ninja: Entering directory `/home/wxl/Downloads/mutter-x11-scaling/src/build'
[239/1366] Compiling C object clutter/clutter/libmutter-clutter-11.so.0.0.0.p/cally_cally-util.c.o
In file included from /usr/include/glib-2.0/glib/giochannel.h:36,
                 from /usr/include/glib-2.0/glib.h:56,
                 from ../mutter/cogl/cogl/cogl-types.h:45,
                 from ../mutter/cogl/cogl/cogl-object.h:34,
                 from ../mutter/cogl/cogl/cogl.h:60,
                 from ../mutter/clutter/clutter/clutter-types.h:32,
                 from ../mutter/clutter/clutter/clutter.h:31,
                 from ../mutter/clutter/clutter/cally/cally-util.c:44:
../mutter/clutter/clutter/cally/cally-util.c: In function ‘atk_key_event_from_clutter_event_key’:
/usr/include/glib-2.0/glib/gstring.h:72:5: warning: ignoring return value of ‘g_string_free_and_steal’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   68 |   (__builtin_constant_p (free_segment) ?        \
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   69 |     ((free_segment) ?                           \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   70 |       (g_string_free) ((str), (free_segment)) : \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   71 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |     :                                           \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |     (g_string_free) ((str), (free_segment)))
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../mutter/clutter/clutter/cally/cally-util.c:228:7: note: in expansion of macro ‘g_string_free’
  228 |       g_string_free (new, FALSE);
      |       ^~~~~~~~~~~~~
[346/1366] Generating cogl/cogl/Cogl-11.gir with a custom command (wrapped by meson to set env)
FAILED: cogl/cogl/Cogl-11.gir 
env PKG_CONFIG_PATH=/home/wxl/Downloads/mutter-x11-scaling/src/build/meson-uninstalled /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=Cogl --nsversion=11 --warn-all --output cogl/cogl/Cogl-11.gir --c-include=cogl/cogl.h --quiet -U_GNU_SOURCE -UCOGL_COMPILATION -D__COGL_H_INSIDE__ -D__COGL_XLIB_H_INSIDE__ -D__COGL_EGL_H_INSIDE__ -D__COGL_GLX_H_INSIDE__ -DCOGL_GIR_SCANNING -I/home/wxl/Downloads/mutter-x11-scaling/src/mutter/cogl/cogl -I/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/cogl -I/home/wxl/Downloads/mutter-x11-scaling/src/mutter/cogl/. -I/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/. -I/home/wxl/Downloads/mutter-x11-scaling/src/mutter/cogl/cogl -I/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/cogl --filelist=/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/cogl/libmutter-cogl-11.so.0.0.0.p/Cogl_11_gir_filelist --include=cairo-1.0 --include=GL-1.0 --include=GObject-2.0 --include=Graphene-1.0 --cflags-begin -D_GNU_SOURCE -I/home/wxl/Downloads/mutter-x11-scaling/src/mutter/cogl/. -I/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/. -I/home/wxl/Downloads/mutter-x11-scaling/src/mutter/cogl/cogl -I/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/cogl -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/graphene-1.0 -I/usr/lib/graphene-1.0/include -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gobject-introspection-1.0 --cflags-end --add-include-path=/usr/share/gir-1.0 -L/home/wxl/Downloads/mutter-x11-scaling/src/build/cogl/cogl --library mutter-cogl-11 -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lgraphene-1.0 -lwayland-server -lEGL -lX11 -lGL -lGLESv2 -lcairo -lgmodule-2.0 -lgdk_pixbuf-2.0 -lsysprof-capture-4 -lXext -lXfixes -lXdamage -lXcomposite -lXrandr -lm -lgirepository-1.0
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 98, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 34, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
[359/1366] Compiling C object src/libmutter-11.so.0.0.0.p/backends_meta-cursor-sprite-xcursor.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by yummy527** [comment]
Solved.

[Here](https://github.com/AyatanaIndicators/ayatana-ido/issues/56) provides info about this issue and gives solution.

In detail, I deactivate conda and try "makepkg -si" again. It works.
